### ISSUE TITLE
pycuda._driver.LogicError For camera stream

### ISSUE THREAD

**Issue by Jeevi10** [mailrocketsystems/JetsonYolov5#12]
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    detections, t = model.Inference(frame)
  File "/jetson-inference/data/networks/JetsonYolov5/yoloDet.py", line 93, in Inference
    stream = cuda.Stream()
pycuda._driver.LogicError: cuStreamCreate failed: context is destroyed

model runs perfectly with local file and when I feed my live camera I am getting this above error. Can someone guide me about this issue. I appreciate your help

**Comment by RN0H** [comment]
I am facing the same issue

**Comment by RN0H** [comment]
> Traceback (most recent call last): File "app.py", line 32, in detections, t = model.Inference(frame) File "/jetson-inference/data/networks/JetsonYolov5/yoloDet.py", line 93, in Inference stream = cuda.Stream() pycuda._driver.LogicError: cuStreamCreate failed: context is destroyed
> 
> model runs perfectly with local file and when I feed my live camera I am getting this above error. Can someone guide me about this issue. I appreciate your help

I was able to solve this issue, by using pyrealsense2. I created a seperate pipeline for streaming that did not involve cuda context handling. Previously I was subscribing to a rostopic for camera images, and I tried to handle the context, but it was giving me cuda driver errors. I do not know the exact solution to the ros subscriber method. Nevertheless, I am sticking to using pyrealsense2 rather than ros for this one.
