### ISSUE TITLE
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1

### ISSUE THREAD

**Issue by VietNguyenHoang812** [mailrocketsystems/JetsonYolov5#7]
I have followed the tutorial and run successfully with "./yolo_det -d custom_model.engine ../images" but when I tried with "python3 app.py", this error occurs:
[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin YoloLayer_TRT version 1
[TensorRT] ERROR: safeDeserializationUtils.cpp (323) - Serialization Error in load: 0 (Cannot deserialize plugin since corresponding IPluginCreator not found in Plugin Registry)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    model = YoloTRT(library="yolov5/build/libmyplugins.so", engine="yolov5/build/license_plate_detection.engine", conf=0.5, yolo_ver="v5")
  File "/home/jetson/Documents/JetsonYolov5_backup/yoloDet.py", line 39, in __init__
    self.batch_size = self.engine.max_batch_size
AttributeError: 'NoneType' object has no attribute 'max_batch_size'

**Comment by VietNguyenHoang812** [comment]
My bad, I modified the code and forgot to change it back
